version: "3"

services:
  web:
    container_name: electionbuddy_dev
    build: .
    volumes:
      - .:/opt/application:delegated
      - bundle_path:/bundle:delegated
    environment:
      BUNDLE_PATH: /bundle/vendor
    ports:
      - 3000:3000
    command: bundle exec rails server -p 3000 -b 0.0.0.0

volumes:
  bundle_path:
